# -*- coding: utf-8 -*-
"""entorno.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gJ4a_ABKjVF7nJXRueNbk3obw2P3u205
"""

# !pip install osmnx

import osmnx as ox
lugar = "Centro, Monterrey, Nuevo Leon, Mexico"
grafo = ox.graph_from_place(lugar, network_type="drive")
ox.plot_graph(grafo)

import json
import random
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data"

pedidos = []

# Generamos 10 pedidos aleatorios en Monterrey
for i in range(1, 11):
    pedido = {
        "pedido_id": 100 + i,
        "origen": [round(25.6866 + random.uniform(-0.02, 0.02), 4), round(-100.3161 + random.uniform(-0.02, 0.02), 4)],
        "destino": [round(25.6500 + random.uniform(-0.02, 0.02), 4), round(-100.2900 + random.uniform(-0.02, 0.02), 4)],
        "pago_mxn": round(random.uniform(45.0, 150.0), 2),
        "distancia_km": round(random.uniform(1.5, 8.0), 1),
        "tiempo_est_min": random.randint(10, 35),
        "ventana_aceptacion_seg": 30
    }
    pedidos.append(pedido)

# Crear el archivo JSON
with open(DATA_DIR / 'pedidos_monterrey.json', 'w') as archivo:
    json.dump(pedidos, archivo, indent=4)

print("¡Éxito! El archivo 'pedidos_monterrey.json' se ha creado.")

import networkx as nx

# Tomamos dos nodos (cruces de calles) al azar de tu mapa generado
nodos = list(grafo.nodes())
origen_nodo = nodos[0]
destino_nodo = nodos[150] # Elegimos un nodo distinto para que haya distancia

# Calculamos la ruta más corta usando el algoritmo matemático
ruta = nx.shortest_path(grafo, origen_nodo, destino_nodo, weight='length')
distancia_metros = nx.shortest_path_length(grafo, origen_nodo, destino_nodo, weight='length')

# Convertimos los metros a kilómetros para la lectura
distancia_km = round(distancia_metros / 1000, 2)
print(f"Distancia real de conducción: {distancia_km} km")

# Dibujamos la ruta exacta sobre el mapa para verificarla
fig, ax = ox.plot_graph_route(grafo, ruta, route_linewidth=6, node_size=0, bgcolor='k')

import random

def calcular_tiempo_con_imprevistos(distancia_km, clima="normal", trafico="ligero"):
    # Velocidad promedio base en la ciudad (ej. 1.5 minutos por cada kilómetro recorrido)
    tiempo_base_minutos = distancia_km * 1.5

    # 1. Simulación de Clima
    if clima == "lluvia":
        tiempo_base_minutos *= 1.4  # La lluvia hace el viaje 40% más lento

    # 2. Simulación de Tráfico / Calles cerradas
    if trafico == "pesado":
        tiempo_base_minutos *= 1.6  # Tráfico pesado suma 60% más tiempo
    elif trafico == "calle_cerrada":
        tiempo_base_minutos += 15.0 # Un rodeo por accidente suma 15 mins fijos

    return round(tiempo_base_minutos)

# --- PRUEBA DE TU CÓDIGO ---
distancia_ejemplo = 1.64 # Usamos el dato de tu mapa
print(f"Viaje de {distancia_ejemplo} km en condiciones normales: {calcular_tiempo_con_imprevistos(distancia_ejemplo)} minutos")
print(f"Viaje de {distancia_ejemplo} km con LLUVIA y TRÁFICO PESADO: {calcular_tiempo_con_imprevistos(distancia_ejemplo, clima='lluvia', trafico='pesado')} minutos")

pedidos_pico = []

# Generamos 20 pedidos urgentes que pagan mucho más (Tarifa Dinámica)
for i in range(1, 21):
    pedido = {
        "pedido_id": 500 + i, # IDs del 500 en adelante para distinguirlos
        "origen": [round(25.6700 + random.uniform(-0.005, 0.005), 4), round(-100.3000 + random.uniform(-0.005, 0.005), 4)],
        "destino": [round(25.6500 + random.uniform(-0.02, 0.02), 4), round(-100.2900 + random.uniform(-0.02, 0.02), 4)],
        "pago_mxn": round(random.uniform(150.0, 300.0), 2), # Pagan el doble o triple
        "distancia_km": round(random.uniform(2.0, 5.0), 1),
        "tiempo_est_min": random.randint(15, 45),
        "ventana_aceptacion_seg": 15 # Tienen menos tiempo para aceptar (urgencia)
    }
    pedidos_pico.append(pedido)

# Exportamos este evento especial a otro JSON
with open(DATA_DIR / 'evento_pico_demanda.json', 'w') as archivo:
    json.dump(pedidos_pico, archivo, indent=4)

print("¡Archivo 'evento_pico_demanda.json' generado!")